services:
  presto-base-volumes:
    volumes:
      - ${PRESTO_DATA_DIR:-.}/hive_metastore:/var/lib/presto/data/hive/metastore
      - ../../common/testing/integration_tests/data:/var/lib/presto/data/hive/data/integration_test
      - ${PRESTO_DATA_DIR:-/dev/null}:/var/lib/presto/data/hive/data/user_data
      - ${LOGS_DIR:-/dev/null}:/opt/presto-server/logs
      - ./launch_presto_servers.sh:/opt/launch_presto_servers.sh:ro

  presto-base-java:
    extends:
      service: presto-base-volumes
    build:
      context: ../../../presto/docker

  presto-base-coordinator:
    extends:
      service: presto-base-java
    container_name: presto-coordinator
    image: presto-coordinator:${PRESTO_IMAGE_TAG}
    ports:
      - 8080:8080
    environment:
      - SERVER_START_TIMESTAMP=${SERVER_START_TIMESTAMP:-}
    volumes:
      - ./launch_coordinator.sh:/opt/launch_coordinator.sh:ro
    entrypoint: ["bash", "/opt/launch_coordinator.sh"]
    command: []

  presto-base-native-worker:
    extends:
      service: presto-base-volumes
    build:
      context: ../../..
      dockerfile: velox-testing/presto/docker/native_build.dockerfile
    environment:
      - GLOG_logtostderr=1
      - SERVER_START_TIMESTAMP=${SERVER_START_TIMESTAMP:-}
