services:
  velox-adapters-build:
    container_name: velox-adapters-build
    image: velox-adapters-build:latest
    build:
      context: ../../..
      dockerfile: velox-testing/velox/docker/adapters_build.dockerfile
    runtime: nvidia
    volumes:
      - ../../../velox:/workspace/velox
      - ${CCACHE_DIR:-/tmp/ccache}:/ccache
    environment:
      - CCACHE_DIR=/ccache
    working_dir: /workspace/velox 
