services:
  velox-adapters-build:
    container_name: velox-adapters-build
    image: velox-adapters-build:latest
    build:
      context: ../../..
      dockerfile: velox-testing/velox/docker/adapters_build.dockerfile
      args:
        TREAT_WARNINGS_AS_ERRORS: ${TREAT_WARNINGS_AS_ERRORS:-0}
    runtime: nvidia
    volumes:
      - ../../../velox:/workspace/velox
      - ${CCACHE_DIR:-/tmp/ccache}:/ccache
    environment:
      - CCACHE_DIR=/ccache
    working_dir: /workspace/velox 
