name: Velox Setup
description: Checkout velox-testing and Velox repos and resolve Velox commit SHA

inputs:
  repository:
    description: Velox repository
    required: true
    default: facebookincubator/velox
  velox_commit:
    description: Velox commit SHA or branch
    required: true
    default: main

outputs:
  velox_sha:
    description: Resolved Velox commit SHA
    value: ${{ steps.resolve-sha.outputs.velox_sha }}

runs:
  using: composite
  steps:
    - name: Checkout Velox
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.velox_commit }}
        path: velox

    - id: resolve-sha
      name: Get Velox commit SHA
      shell: bash
      run: |
        VELOX_REF="${{ inputs.velox_commit }}"
        echo "Input ref: $VELOX_REF"
        
        if [[ "$VELOX_REF" == "main" || "$VELOX_REF" == "master" ]]; then
          cd velox
          ACTUAL_SHA=$(git rev-parse HEAD)
          echo "Resolved SHA for branch '$VELOX_REF': $ACTUAL_SHA"
          echo "VELOX_COMMIT_SHA=$ACTUAL_SHA" >> $GITHUB_ENV
          echo "velox_sha=$ACTUAL_SHA" >> $GITHUB_OUTPUT
        else
          echo "Using provided ref: $VELOX_REF"
          echo "VELOX_COMMIT_SHA=$VELOX_REF" >> $GITHUB_ENV
          echo "velox_sha=$VELOX_REF" >> $GITHUB_OUTPUT
        fi
