CREATE TABLE hive.tpcds_test.store_returns (
    sr_returned_date_sk INTEGER,
    sr_return_time_sk INTEGER,
    sr_item_sk INTEGER,
    sr_customer_sk INTEGER,
    sr_cdemo_sk INTEGER,
    sr_hdemo_sk INTEGER,
    sr_addr_sk INTEGER,
    sr_store_sk INTEGER,
    sr_reason_sk INTEGER,
    sr_ticket_number INTEGER,
    sr_return_quantity INTEGER,
    sr_return_amt DOUBLE,
    sr_return_tax DOUBLE,
    sr_return_amt_inc_tax DOUBLE,
    sr_fee DOUBLE,
    sr_return_ship_cost DOUBLE,
    sr_refunded_cash DOUBLE,
    sr_reversed_charge DOUBLE,
    sr_store_credit DOUBLE,
    sr_net_loss DOUBLE
) WITH (FORMAT = 'PARQUET', EXTERNAL_LOCATION = 'file:{file_path}')
