name: 'Setup sccache for CI'
description: 'Configure sccache with OIDC-based AWS credentials for S3 caching and optional distributed compilation'

inputs:
  role-to-assume:
    description: 'AWS IAM role ARN for OIDC authentication'
    required: false
    default: ''
  aws-region:
    description: 'AWS region for the sccache S3 bucket'
    required: false
    default: 'us-east-2'
  dist-auth-token:
    description: 'GitHub token for sccache distributed compilation scheduler auth. When empty, dist compile is disabled.'
    required: false
    default: ''
  enable-dist:
    description: 'Enable sccache distributed compilation (requires dist-auth-token)'
    required: false
    default: 'false'

outputs:
  enabled:
    description: 'Whether sccache was successfully configured'
    value: ${{ steps.finalize.outputs.enabled }}
  dist-enabled:
    description: 'Whether distributed compilation is enabled'
    value: ${{ steps.finalize.outputs.dist_enabled }}

runs:
  using: composite
  steps:
    - name: Check if OIDC configuration is available
      id: check-config
      shell: bash
      run: |
        if [[ -z "${{ inputs.role-to-assume }}" ]]; then
          echo "::warning::No AWS role ARN provided, sccache will be disabled"
          echo "available=false" >> "$GITHUB_OUTPUT"
        else
          echo "AWS role ARN provided, attempting OIDC authentication"
          echo "available=true" >> "$GITHUB_OUTPUT"
        fi

    - name: Configure AWS Credentials via OIDC
      id: aws-creds
      if: steps.check-config.outputs.available == 'true'
      uses: aws-actions/configure-aws-credentials@v4
      continue-on-error: true
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.aws-region }}
        role-duration-seconds: 43200

    - name: Create sccache auth files
      id: finalize
      shell: bash
      run: |
        if [[ "${{ steps.check-config.outputs.available }}" != "true" || "${{ steps.aws-creds.outcome }}" != "success" ]]; then
          echo "::warning::sccache setup failed or OIDC not available. Building without sccache."
          echo "enabled=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        # Create sccache auth directory
        SCCACHE_AUTH_DIR="${HOME}/.sccache-auth"
        mkdir -p "${SCCACHE_AUTH_DIR}"

        # Write AWS credentials in CLI INI format
        cat > "${SCCACHE_AUTH_DIR}/aws_credentials" <<CREDEOF
        [default]
        aws_access_key_id = ${AWS_ACCESS_KEY_ID}
        aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}
        aws_session_token = ${AWS_SESSION_TOKEN}
        CREDEOF
        # Strip leading whitespace from credentials file (from YAML indentation)
        sed -i 's/^[[:space:]]*//' "${SCCACHE_AUTH_DIR}/aws_credentials"

        # Write github_token for dist compile auth (real token or placeholder)
        DIST_ENABLED="false"
        if [[ "${{ inputs.enable-dist }}" == "true" && -n "${{ inputs.dist-auth-token }}" ]]; then
          echo "${{ inputs.dist-auth-token }}" > "${SCCACHE_AUTH_DIR}/github_token"
          DIST_ENABLED="true"
          echo "Distributed compilation enabled with provided auth token"
        else
          echo "placeholder-ci-no-dist-compile" > "${SCCACHE_AUTH_DIR}/github_token"
          echo "Distributed compilation disabled (no token or enable-dist=false)"
        fi

        # Export auth dir for downstream steps
        echo "SCCACHE_AUTH_DIR=${SCCACHE_AUTH_DIR}" >> "$GITHUB_ENV"

        echo "enabled=true" >> "$GITHUB_OUTPUT"
        echo "dist_enabled=${DIST_ENABLED}" >> "$GITHUB_OUTPUT"
        echo "sccache auth files created in ${SCCACHE_AUTH_DIR}"
