coordinator=false
http-server.http.port=8080
discovery.uri=http://localhost:8080
presto.version=testversion
system-memory-gb=8
query-memory-gb=6
memory-arbitrator-kind=SHARED
task.max-drivers-per-task=2
runtime-metrics-collection-enabled=true
cudf.enabled=true
cudf.exchange=false
cudf.memory_resource=async
async-data-cache-enabled=false
