# New option in 0.282 to control inference of NOT NULL columns in joins (undocumented).
optimizer.joins-not-null-inference-strategy=USE_FUNCTION_METADATA
# Use a default filter factor to estimate the selectivity of filters in queries.
optimizer.default-filter-factor-enabled=true
cluster-tag=native-gpu
