hive.file-splittable=true

hive.max-outstanding-splits=1800
hive.max-initial-splits=600
hive.max-initial-split-size=128MB
hive.max-split-size=256MB
hive.split-loader-concurrency=32
hive.pushdown-filter-enabled=true
