#!/bin/bash

# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

set -e

function install_miniforge3() {
  echo "Install miniforge3..."
  TEMP_DIR=$(mktemp -d)
  trap "rm -rf $TEMP_DIR" EXIT

  pushd $TEMP_DIR
  curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
  bash Miniforge3-$(uname)-$(uname -m).sh -b -p "$MINIFORGE_HOME"
  popd
  echo "miniforge3 installation completed"
}

# Based on the script generated by `conda init bash`
function init_conda() {
  echo "Initializing conda.."
  __conda_setup=$($MINIFORGE_HOME/bin/conda 'shell.bash' 'hook')
  if [ $? -eq 0 ]; then
    eval "$__conda_setup"
  else
    if [ -f "$MINIFORGE_HOME/etc/profile.d/conda.sh" ]; then
      . "$MINIFORGE_HOME/etc/profile.d/conda.sh"
    else
      export PATH="$MINIFORGE_HOME/bin:$PATH"
    fi
  fi
  unset __conda_setup
  LOCAL_CONDA_INIT=true # keep track of whether we set up the current conda environment
  echo "Conda initialization completed"
}

function activate_python_virtual_env() {
  local venv_dir=${1:-".venv"}

  if [[ -d "$venv_dir/conda-meta" ]]; then
    echo "Activating conda environment"
    conda activate "$(readlink -f $venv_dir)"
  elif [[ -f "$venv_dir/pyvenv.cfg" ]]; then
    echo "Activating venv environment"
    source $venv_dir/bin/activate
  else
    echo "Error: $venv_dir is not a valid virtual environment"
    exit 1
  fi
}

function init_python_virtual_env() {
  local venv_dir=${1:-".venv"}
  rm -rf $venv_dir

  if python3 -m venv $venv_dir &>/dev/null; then
    echo "Created virtual environment using the venv module"
  else
    if [[ -z $MINIFORGE_HOME ]]; then
        echo "Error: MINIFORGE_HOME must be set when attempting to create a virtual environment with conda"
        exit 1
    fi

    CONDA_BIN=$MINIFORGE_HOME/bin/conda
    if [[ ! -x "$CONDA_BIN" ]]; then
        install_miniforge3
    fi

    init_conda

    echo "Creating virtual environment using conda"
    # This needs to be python 3.10 because there is an issue with ARM conda's python 3.12.
    conda create -q -y --prefix "$venv_dir" python=3.11 > /dev/null
  fi

  activate_python_virtual_env $venv_dir
}

function delete_python_virtual_env() {
  local venv_dir=${1:-".venv"}

  if [ -n "$LOCAL_CONDA_INIT" ] && command -v conda &> /dev/null; then
      echo "Deactivating conda environment"
      conda deactivate
      LOCAL_CONDA_INIT=""
  elif command -v deactivate &> /dev/null; then
    echo "Deactivating venv environment"
    deactivate
  fi

  echo "Deleting $venv_dir directory"
  rm -rf $venv_dir
}
