#!/bin/bash

# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

set -e

function install_miniforge3() {
  echo "Install miniforge3..."
  TEMP_DIR=$(mktemp -d)
  trap "rm -rf $TEMP_DIR" EXIT

  pushd $TEMP_DIR
  curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
  bash Miniforge3-$(uname)-$(uname -m).sh -b -p "$MINIFORGE_HOME"
  popd
  echo "miniforge3 installation completed"
}

# Based on the script generated by `conda init bash`
function init_conda() {
  echo "Initializing conda.."
  __conda_setup=$($MINIFORGE_HOME/bin/conda 'shell.bash' 'hook')
  if [ $? -eq 0 ]; then
    eval "$__conda_setup"
  else
    if [ -f "$MINIFORGE_HOME/etc/profile.d/conda.sh" ]; then
      . "$MINIFORGE_HOME/etc/profile.d/conda.sh"
    else
      export PATH="$MINIFORGE_HOME/bin:$PATH"
    fi
  fi
  unset __conda_setup
  LOCAL_CONDA_INIT=true # keep track of whether we set up the current conda environment
  echo "Conda initialization completed"
}

function init_python_virtual_env() {
  rm -rf .venv

  if python3.12 -m venv .venv; then
    echo "Created virtual environment using the venv module"

    echo "Activating venv environment"
    source .venv/bin/activate
  else
    if [[ -z $MINIFORGE_HOME ]]; then
        echo "Error: MINIFORGE_HOME must be set when attempting to create a virtual environment with conda"
        exit 1
    fi

    CONDA_BIN=$MINIFORGE_HOME/bin/conda
    if [[ ! -x "$CONDA_BIN" ]]; then
        install_miniforge3
    fi

    init_conda

    echo "Creating virtual environment using conda"
    conda create -q -y --prefix ".venv" python=3.12 > /dev/null

    echo "Activating conda environment"
    conda activate "$(readlink -f .venv)"
  fi
}

function delete_python_virtual_env() {
  if [ -n "$LOCAL_CONDA_INIT" ] && command -v conda &> /dev/null; then
      echo "Deactivating conda environment"
      conda deactivate
      LOCAL_CONDA_INIT=""
  elif command -v deactivate &> /dev/null; then
    echo "Deactivating venv environment"
    deactivate
  fi

  echo "Deleting .venv directory"
  rm -rf .venv
}
