#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""
Nightly Failure Root Cause Analysis — Upstream Issue/PR Search

Parses a status.txt nightly report (generated by check_nightly_status.py),
extracts error signatures from each failure's stacktrace, searches upstream
GitHub repos for related issues/PRs, and outputs a Slack-formatted RCA report.

Requirements:
  - gh (GitHub CLI), authenticated
  - Python 3.9+

Usage:
  python scripts/search_upstream_issues.py [OPTIONS]

Options:
  -i, --input PATH        Path to status.txt (default: status.txt)
  -o, --output PATH       Path to write the RCA report (default: stdout)
  --days N                Search issues/PRs created within the last N days (default: 90)
  --max-results N         Max results per search query per repo (default: 5)
  --repos REPO [REPO ...] Additional repos to search
  --self-repo REPO        The repo that owns the nightly workflows (default: rapidsai/velox-testing)
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone

# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------


@dataclass
class Stacktrace:
    text: str
    cause: str = ""
    fix: str = ""


@dataclass
class Failure:
    number: int
    title: str
    workflow: str = ""
    run_url: str = ""
    also_fails_in: str = ""
    conclusion: str = ""
    job_name: str = ""
    step_name: str = ""
    stacktraces: list[Stacktrace] = field(default_factory=list)


@dataclass
class SearchResult:
    repo: str
    number: int
    title: str
    url: str
    kind: str  # "issue" or "pr"
    state: str = ""


# ---------------------------------------------------------------------------
# Status.txt parser
# ---------------------------------------------------------------------------

_FAILURE_HEADING = re.compile(r"^\*(\d+)\.\s+(.+)\*$")
_METADATA_RE = {
    "workflow": re.compile(r"^•\s*\*Workflow:\*\s*(.+)$"),
    "run_url": re.compile(r"^•\s*\*Run:\*\s*(https?://\S+)"),
    "also_fails_in": re.compile(r"^•\s*\*Also fails in:\*\s*(.+)$"),
    "conclusion": re.compile(r"^•\s*\*Conclusion:\*\s*(\S+)"),
}
_JOB_RE = re.compile(r"^\s*◦\s*Job:\s*`(.+?)`")
_STEP_RE = re.compile(r"^\s*▪︎\s*Step:\s*(.+?)(?:\s*\((?:failure|error)\))?$")
_CAUSE_RE = re.compile(r"^\s*\*Cause:\*\s*_(.+?)_?\s*$")
_FIX_RE = re.compile(r"^\s*\*Fix:\*\s*_(.+?)_?\s*$")


def parse_status_file(path: str) -> list[Failure]:
    with open(path, encoding="utf-8") as f:
        text = f.read()

    # Split on `---` separator lines
    sections = re.split(r"^---\s*$", text, flags=re.MULTILINE)
    failures: list[Failure] = []

    for section in sections:
        lines = section.strip().splitlines()
        if not lines:
            continue

        heading_match = None
        for i, line in enumerate(lines):
            heading_match = _FAILURE_HEADING.match(line.strip())
            if heading_match:
                lines = lines[i:]
                break
        if not heading_match:
            continue

        fail = Failure(
            number=int(heading_match.group(1)),
            title=heading_match.group(2),
        )

        in_stacktrace = False
        stacktrace_lines: list[str] = []
        current_cause = ""
        current_fix = ""

        for line in lines[1:]:
            stripped = line.strip()

            # Check for code fence
            if stripped.startswith("```"):
                if in_stacktrace:
                    fail.stacktraces.append(
                        Stacktrace(
                            text="\n".join(stacktrace_lines),
                        )
                    )
                    stacktrace_lines = []
                    in_stacktrace = False
                else:
                    in_stacktrace = True
                continue

            if in_stacktrace:
                stacktrace_lines.append(line)
                continue

            # Parse metadata
            for key, pattern in _METADATA_RE.items():
                m = pattern.match(stripped)
                if m:
                    setattr(fail, key, m.group(1))
                    break

            m = _JOB_RE.match(stripped)
            if m:
                fail.job_name = m.group(1)
                continue

            m = _STEP_RE.match(stripped)
            if m:
                fail.step_name = m.group(1)
                continue

            m = _CAUSE_RE.match(stripped)
            if m:
                current_cause = m.group(1)
                if fail.stacktraces:
                    fail.stacktraces[-1].cause = current_cause
                continue

            m = _FIX_RE.match(stripped)
            if m:
                current_fix = m.group(1)
                if fail.stacktraces:
                    fail.stacktraces[-1].fix = current_fix
                continue

        if fail.stacktraces or fail.title:
            failures.append(fail)

    return failures


# ---------------------------------------------------------------------------
# Keyword extraction
# ---------------------------------------------------------------------------

_GTEST_FAILED = re.compile(r"\[\s*FAILED\s*\]\s+(\w+\.\w+)")
_CPP_ERROR = re.compile(r"error:\s+'(\w+)'\s+is not a member of\s+'([\w:]+)'")
_CPP_GENERIC_ERROR = re.compile(r"error:\s+(.{10,80})")
_PACKAGE_INSTALL = re.compile(r"(?:dnf|yum|apt-get)\s+install\s+-y\s+([\w.-]+)")
_FAILED_TARGET = re.compile(r"^FAILED:\s+(\S+)")
_DOCKERFILE_REF = re.compile(r"(\w+\.dockerfile):\d+")
_FUNCTION_SIG = re.compile(r"Scalar function signature is not supported:\s+(\w+)\(([^)]+)\)")


def _classify_repos(failure: Failure) -> list[str]:
    """Determine which upstream repos to search based on failure context."""
    all_text = " ".join(
        [failure.title, failure.job_name, failure.step_name]
        + [st.text for st in failure.stacktraces]
        + [st.cause for st in failure.stacktraces]
    ).lower()

    repos: list[str] = []

    if any(kw in all_text for kw in ("cudf", "experimental/cudf", "cudf_")):
        repos.append("facebookincubator/velox")
    if any(kw in all_text for kw in ("grpc_ep", "arrow_extra", "arrow", "abseil", "absl")):
        repos.append("apache/arrow")
    if any(kw in all_text for kw in ("presto", "prestissimo", "centos-dependency")):
        repos.append("prestodb/presto")
    if any(kw in all_text for kw in ("velox",)):
        if "facebookincubator/velox" not in repos:
            repos.append("facebookincubator/velox")
    if any(kw in all_text for kw in ("cuda", "nsight", "nsys")):
        repos.append("rapidsai/velox-testing")

    if not repos:
        repos = ["facebookincubator/velox", "prestodb/presto"]

    return repos


def extract_search_queries(failure: Failure) -> list[str]:
    """Extract meaningful search queries from a failure's stacktraces."""
    queries: list[str] = []
    all_stacktrace_text = "\n".join(st.text for st in failure.stacktraces)

    # GTest failed test names — highest signal
    for m in _GTEST_FAILED.finditer(all_stacktrace_text):
        test_name = m.group(1)
        queries.append(test_name)
        # Also search just the method name
        if "." in test_name:
            queries.append(test_name.split(".")[-1])

    # C++ compile errors: 'X' is not a member of 'Y'
    for m in _CPP_ERROR.finditer(all_stacktrace_text):
        symbol, namespace = m.group(1), m.group(2)
        queries.append(f"{namespace} {symbol}")

    # Function signature errors (Velox-specific)
    for m in _FUNCTION_SIG.finditer(all_stacktrace_text):
        queries.append(f"{m.group(1)} {m.group(2)}")

    # Package install failures
    for m in _PACKAGE_INSTALL.finditer(all_stacktrace_text):
        queries.append(m.group(1))

    # Dockerfile references
    for m in _DOCKERFILE_REF.finditer(all_stacktrace_text):
        queries.append(m.group(1))

    # Failed build targets (e.g. grpc_ep)
    for m in _FAILED_TARGET.finditer(all_stacktrace_text):
        target = m.group(1).split("/")[-1].split("-")[0]
        if len(target) > 3:
            queries.append(target)

    # Docker volume mount errors
    if "invalid spec:" in all_stacktrace_text:
        queries.append("Docker volume mount")

    # Benchmark data errors
    for m in re.finditer(r"(?:data directory not found|benchmark data)", all_stacktrace_text, re.IGNORECASE):
        queries.append("benchmark data")

    # Broader fallback queries for build/dep errors
    if any(kw in all_stacktrace_text for kw in ("grpc_ep", "grpc_ep-build")):
        queries.append("grpc abseil")
        queries.append("grpc_ep build failed")
    if "nsight-systems" in all_stacktrace_text or "nsight" in all_stacktrace_text:
        queries.append("nsight-systems install")
        queries.append("nsight cuda repo")
    if "cuda-rhel9" in all_stacktrace_text or "cuda repo" in all_stacktrace_text:
        queries.append("cuda repo metadata")

    # From the cause text — extract key noun phrases
    for st in failure.stacktraces:
        if st.cause:
            cause_keywords = _extract_cause_keywords(st.cause)
            queries.extend(cause_keywords)

    # Deduplicate while preserving order, filtering out low-quality queries
    seen: set[str] = set()
    unique: list[str] = []
    for q in queries:
        q = q.strip()
        if not q or q.lower() in seen:
            continue
        # Skip path-like strings, raw error prefixes, overly short terms
        if q.startswith("/") or q.startswith(":") or q.startswith("http"):
            continue
        if len(q) < 4:
            continue
        # Skip strings that look like file paths rather than search terms
        if q.count("/") > 2:
            continue
        seen.add(q.lower())
        unique.append(q)

    return unique[:8]


def _extract_cause_keywords(cause: str) -> list[str]:
    """Extract searchable terms from AI-generated cause text."""
    keywords: list[str] = []

    # Look for backtick-quoted identifiers
    for m in re.finditer(r"`([^`]{3,60})`", cause):
        val = m.group(1)
        if not val.startswith("http") and not val.startswith("/"):
            keywords.append(val)

    # Look for error-related noun phrases
    for m in re.finditer(r"(?:API|version)\s+(?:incompatibility|mismatch)", cause, re.IGNORECASE):
        keywords.append(m.group(0))

    return keywords[:3]


# ---------------------------------------------------------------------------
# GitHub search
# ---------------------------------------------------------------------------


def _run_gh(*args: str, timeout: int = 30) -> str:
    try:
        proc = subprocess.run(
            ["gh", *args],
            capture_output=True,
            text=True,
            timeout=timeout,
        )
        return proc.stdout.strip()
    except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
        return ""


def _search_gh(
    repo: str,
    query: str,
    kind: str,
    since_date: str,
    max_results: int,
) -> list[SearchResult]:
    """Search a single repo for issues or PRs matching the query.

    Tries `gh search` first (global search), then falls back to
    `gh issue/pr list --search` (repo-scoped search) which often
    has better results for short or code-like queries.
    """
    results: list[SearchResult] = []

    # Strategy 1: gh search (global)
    gh_kind = "issues" if kind == "issue" else "prs"
    raw = _run_gh(
        "search",
        gh_kind,
        "--repo",
        repo,
        "--limit",
        str(max_results),
        "--json",
        "title,url,number,state",
        f"{query} created:>={since_date}",
        timeout=60,
    )
    if raw:
        try:
            for it in json.loads(raw):
                results.append(
                    SearchResult(
                        repo=repo,
                        number=it.get("number", 0),
                        title=it.get("title", ""),
                        url=it.get("url", ""),
                        kind=kind,
                        state=it.get("state", "").upper(),
                    )
                )
        except json.JSONDecodeError:
            pass

    # Strategy 2: gh issue/pr list --search (repo-scoped, often better)
    if len(results) < max_results:
        list_cmd = "issue" if kind == "issue" else "pr"
        raw2 = _run_gh(
            list_cmd,
            "list",
            "--repo",
            repo,
            "--search",
            query,
            "--limit",
            str(max_results),
            "--json",
            "title,url,number,state",
            timeout=60,
        )
        if raw2:
            try:
                seen = {r.url for r in results}
                for it in json.loads(raw2):
                    url = it.get("url", "")
                    if url not in seen:
                        seen.add(url)
                        results.append(
                            SearchResult(
                                repo=repo,
                                number=it.get("number", 0),
                                title=it.get("title", ""),
                                url=url,
                                kind=kind,
                                state=it.get("state", "").upper(),
                            )
                        )
            except json.JSONDecodeError:
                pass

    return results[:max_results]


def search_upstream(
    failure: Failure,
    repos: list[str],
    since_date: str,
    max_results: int,
    extra_repos: list[str] | None = None,
) -> list[SearchResult]:
    """Search all relevant repos for issues/PRs related to a failure."""
    all_repos = list(repos)
    if extra_repos:
        for r in extra_repos:
            if r not in all_repos:
                all_repos.append(r)

    queries = extract_search_queries(failure)
    if not queries:
        return []

    seen_urls: set[str] = set()
    all_results: list[SearchResult] = []

    tasks = []
    with ThreadPoolExecutor(max_workers=8) as pool:
        for query in queries[:5]:
            for repo in all_repos:
                for kind in ("issue", "pr"):
                    tasks.append(pool.submit(_search_gh, repo, query, kind, since_date, max_results))
        for fut in as_completed(tasks):
            try:
                for result in fut.result():
                    if result.url not in seen_urls:
                        seen_urls.add(result.url)
                        all_results.append(result)
            except Exception:
                pass

    return all_results


# ---------------------------------------------------------------------------
# Output formatting (Slack mrkdwn)
# ---------------------------------------------------------------------------


def _state_badge(state: str) -> str:
    s = state.upper()
    if s in ("OPEN",):
        return "OPEN"
    if s in ("CLOSED", "MERGED"):
        return "MERGED" if s == "MERGED" else "CLOSED"
    return s


def format_rca_report(
    failures: list[Failure],
    results_by_failure: dict[int, list[SearchResult]],
    date_str: str,
) -> str:
    """Produce Slack-formatted RCA report."""
    lines: list[str] = []

    try:
        dt = datetime.strptime(date_str, "%Y-%m-%d")
        formatted_date = dt.strftime("%B %d, %Y")
    except Exception:
        formatted_date = date_str

    lines.append(f"*🔍 Nightly Failure Root Cause Analysis — {formatted_date}*")
    lines.append("")
    lines.append("*Upstream issues and PRs associated with each nightly failure.*")
    lines.append("")
    lines.append("---")

    for fail in failures:
        lines.append("")
        lines.append(f"*{fail.number}. {fail.title}*")

        if fail.workflow:
            lines.append(f"• *Workflow:* {fail.workflow}")
        if fail.run_url:
            lines.append(f"• *Run:* {fail.run_url}")
        if fail.also_fails_in:
            lines.append(f"• *Also fails in:* {fail.also_fails_in}")

        # Error summary from stacktraces
        error_summary = _build_error_summary(fail)
        if error_summary:
            lines.append(f"• *Error:* {error_summary}")

        # Search results grouped by repo
        results = results_by_failure.get(fail.number, [])
        if results:
            by_repo: dict[str, list[SearchResult]] = {}
            for r in results:
                by_repo.setdefault(r.repo, []).append(r)

            lines.append("")
            lines.append("• *Related Upstream Issues/PRs:*")
            for repo, repo_results in sorted(by_repo.items()):
                lines.append(f"  _`{repo}`_:")
                for r in repo_results[:3]:
                    kind_label = "PR" if r.kind == "pr" else "Issue"
                    state_label = _state_badge(r.state)
                    lines.append(f"  ◦ [{kind_label}] #{r.number} — {r.title} ({state_label})")
                    lines.append(f"    {r.url}")
        else:
            lines.append("")
            lines.append(
                "• *Related Upstream Issues/PRs:* _No matching issues/PRs found. This may need a new bug report._"
            )

        # Include the AI-generated cause/fix from status.txt
        causes = [st.cause for st in fail.stacktraces if st.cause and "Unable to" not in st.cause]
        fixes = [st.fix for st in fail.stacktraces if st.fix and "Unable to" not in st.fix]

        if causes:
            lines.append("")
            cause_text = causes[0]
            if len(cause_text) > 1000:
                cause_text = cause_text[:997] + "..."
            lines.append(f"• *Root Cause:* _{cause_text}_")

        if fixes:
            fix_text = fixes[0]
            if len(fix_text) > 1000:
                fix_text = fix_text[:997] + "..."
            lines.append(f"• *Suggested Fix:* _{fix_text}_")

        lines.append("")
        lines.append("---")

    return "\n".join(lines)


def _build_error_summary(fail: Failure) -> str:
    """Build a one-line error summary from the stacktraces."""
    summaries: list[str] = []
    for st in fail.stacktraces:
        text = st.text
        if not text.strip():
            continue

        # GTest failure
        m = _GTEST_FAILED.search(text)
        if m:
            summaries.append(f"`{m.group(1)}`")
            continue

        # C++ compile error
        m = _CPP_ERROR.search(text)
        if m:
            summaries.append(f"`{m.group(1)}` not a member of `{m.group(2)}`")
            continue

        # Generic error line
        m = _CPP_GENERIC_ERROR.search(text)
        if m:
            summaries.append(f"`{m.group(1).strip()}`")
            continue

        # First meaningful error line
        for line in text.splitlines():
            line = line.strip()
            if any(kw in line.lower() for kw in ("error", "failed", "fatal")):
                clean = re.sub(r"^#\d+\s+[\d.]+\s*", "", line).strip()
                if clean and len(clean) > 10:
                    summaries.append(f"`{clean[:120]}`")
                    break

    seen: set[str] = set()
    unique = []
    for s in summaries:
        if s not in seen:
            seen.add(s)
            unique.append(s)

    return ", ".join(unique[:3]) if unique else ""


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Search upstream repos for issues/PRs related to nightly failures",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument(
        "-i",
        "--input",
        default="status.txt",
        help="Path to the nightly status.txt file (default: status.txt)",
    )
    p.add_argument(
        "-o",
        "--output",
        default=None,
        help="Path to write the RCA report (default: stdout only)",
    )
    p.add_argument(
        "--days",
        type=int,
        default=90,
        help="Search issues/PRs created within the last N days (default: 90)",
    )
    p.add_argument(
        "--max-results",
        type=int,
        default=5,
        help="Max results per search query per repo (default: 5)",
    )
    p.add_argument(
        "--repos",
        nargs="+",
        default=[],
        help="Additional repos to search (e.g. rapidsai/cudf)",
    )
    p.add_argument(
        "--self-repo",
        default="rapidsai/velox-testing",
        help="The repo that owns the nightly workflows (default: rapidsai/velox-testing)",
    )
    return p.parse_args()


def main():
    args = parse_args()

    print(f"Parsing {args.input}...", file=sys.stderr)
    failures = parse_status_file(args.input)
    if not failures:
        print("No failures found in status file.", file=sys.stderr)
        sys.exit(0)

    print(f"Found {len(failures)} failure(s). Searching upstream repos...", file=sys.stderr)

    since_date = (datetime.now(timezone.utc) - timedelta(days=args.days)).strftime("%Y-%m-%d")
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    results_by_failure: dict[int, list[SearchResult]] = {}

    for fail in failures:
        repos = _classify_repos(fail)
        if args.self_repo and args.self_repo not in repos:
            repos.append(args.self_repo)

        queries = extract_search_queries(fail)
        query_preview = ", ".join(f'"{q}"' for q in queries[:3])
        repo_preview = ", ".join(repos)
        print(
            f"  [{fail.number}] {fail.title}\n      Repos: {repo_preview}\n      Queries: {query_preview}",
            file=sys.stderr,
        )

        results = search_upstream(
            failure=fail,
            repos=repos,
            since_date=since_date,
            max_results=args.max_results,
            extra_repos=args.repos,
        )
        results_by_failure[fail.number] = results
        print(f"      → {len(results)} result(s)", file=sys.stderr)

    report = format_rca_report(failures, results_by_failure, date_str)

    print(report)
    if args.output:
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(report)
        print(f"\nReport written to {args.output}", file=sys.stderr)


if __name__ == "__main__":
    main()
