# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

"""Drop and recreate all tables in a Hive schema from scratch.

Combines the logic from create_hive_tables.py and analyze_tables.py into a
single operation that guarantees a clean Presto state:

1. Drop all existing tables and the schema (if it exists)
2. Recreate the schema
3. Recreate all tables from DDL generated by generate_table_schemas.py
4. Optionally run ANALYZE on all tables
"""

import argparse
import os
import shutil
import subprocess
import sys
import tempfile

import prestodb

from create_hive_tables import create_tables
from analyze_tables import analyze_tables


def drop_and_recreate(
    host,
    port,
    user,
    schema_name,
    benchmark_type,
    data_dir_name,
    presto_data_dir,
    skip_analyze,
    verbose,
):
    repo_root = os.path.normpath(
        os.path.join(os.path.dirname(__file__), "..", "..", "..")
    )
    schema_gen_script = os.path.join(
        repo_root, "benchmark_data_tools", "generate_table_schemas.py"
    )
    run_py_script = os.path.join(repo_root, "scripts", "run_py_script.sh")
    data_path = os.path.join(presto_data_dir, data_dir_name)

    if not os.path.isdir(data_path):
        raise FileNotFoundError(
            f"Dataset directory does not exist: {data_path}"
        )

    temp_schema_dir = tempfile.mkdtemp(prefix="schema_gen_")
    try:
        if verbose:
            print(f"Generating table schemas from: {data_path}")
        subprocess.run(
            [
                run_py_script,
                "-p", schema_gen_script,
                "--benchmark-type", benchmark_type,
                "--schemas-dir-path", temp_schema_dir,
                "--data-dir-name", data_path,
            ],
            check=True,
        )

        if verbose:
            print(f"Connecting to Presto at {host}:{port} as '{user}'")
        conn = prestodb.dbapi.connect(
            host=host, port=port, user=user, catalog="hive"
        )
        cursor = conn.cursor()

        try:
            if verbose:
                print(f"Dropping and recreating schema '{schema_name}'...")
            data_sub_directory = f"user_data/{data_dir_name}"
            create_tables(cursor, schema_name, temp_schema_dir, data_sub_directory)
            if verbose:
                print("Schema and tables recreated successfully.")

            if not skip_analyze:
                if verbose:
                    print("Running ANALYZE on all tables...")
                analyze_tables(cursor, schema_name, verbose=verbose)
        finally:
            cursor.close()
            conn.close()
    finally:
        shutil.rmtree(temp_schema_dir, ignore_errors=True)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Drop and recreate all tables in a Hive schema from scratch."
    )
    parser.add_argument(
        "-b", "--benchmark-type", type=str, required=True,
        choices=["tpch", "tpcds"],
        help="Type of benchmark (tpch or tpcds).",
    )
    parser.add_argument(
        "-s", "--schema-name", type=str, required=True,
        help="Name of the Hive schema to drop and recreate.",
    )
    parser.add_argument(
        "-d", "--data-dir-name", type=str, required=True,
        help="Name of the data directory under PRESTO_DATA_DIR.",
    )
    parser.add_argument(
        "--host", type=str, default="localhost",
        help="Presto coordinator hostname (default: localhost).",
    )
    parser.add_argument(
        "--port", type=int, default=8080,
        help="Presto coordinator port (default: 8080).",
    )
    parser.add_argument(
        "--user", type=str, default="test_user",
        help="Presto user (default: test_user).",
    )
    parser.add_argument(
        "--skip-analyze", action="store_true", default=False,
        help="Skip running ANALYZE TABLE after recreation.",
    )
    parser.add_argument(
        "-v", "--verbose", action="store_true", default=False,
        help="Enable verbose output.",
    )
    args = parser.parse_args()

    presto_data_dir = os.environ.get("PRESTO_DATA_DIR")
    if not presto_data_dir:
        print("Error: PRESTO_DATA_DIR environment variable must be set.")
        sys.exit(1)

    drop_and_recreate(
        host=args.host,
        port=args.port,
        user=args.user,
        schema_name=args.schema_name,
        benchmark_type=args.benchmark_type,
        data_dir_name=args.data_dir_name,
        presto_data_dir=presto_data_dir,
        skip_analyze=args.skip_analyze,
        verbose=args.verbose,
    )
