CREATE TABLE hive.{schema}.store_sales (
    ss_sold_date_sk INTEGER,
    ss_sold_time_sk INTEGER,
    ss_item_sk INTEGER,
    ss_customer_sk INTEGER,
    ss_cdemo_sk INTEGER,
    ss_hdemo_sk INTEGER,
    ss_addr_sk INTEGER,
    ss_store_sk INTEGER,
    ss_promo_sk INTEGER,
    ss_ticket_number INTEGER,
    ss_quantity INTEGER,
    ss_wholesale_cost DOUBLE,
    ss_list_price DOUBLE,
    ss_sales_price DOUBLE,
    ss_ext_discount_amt DOUBLE,
    ss_ext_sales_price DOUBLE,
    ss_ext_wholesale_cost DOUBLE,
    ss_ext_list_price DOUBLE,
    ss_ext_tax DOUBLE,
    ss_coupon_amt DOUBLE,
    ss_net_paid DOUBLE,
    ss_net_paid_inc_tax DOUBLE,
    ss_net_profit DOUBLE
) WITH (FORMAT = 'PARQUET', EXTERNAL_LOCATION = 'file:{file_path}')
