CREATE TABLE hive.{schema}.web_site (
    web_site_sk INTEGER,
    web_site_id VARCHAR,
    web_rec_start_date DATE,
    web_rec_end_date DATE,
    web_name VARCHAR,
    web_open_date_sk INTEGER,
    web_close_date_sk INTEGER,
    web_class VARCHAR,
    web_manager VARCHAR,
    web_mkt_id INTEGER,
    web_mkt_class VARCHAR,
    web_mkt_desc VARCHAR,
    web_market_manager VARCHAR,
    web_company_id INTEGER,
    web_company_name VARCHAR,
    web_street_number VARCHAR,
    web_street_name VARCHAR,
    web_street_type VARCHAR,
    web_suite_number VARCHAR,
    web_city VARCHAR,
    web_county VARCHAR,
    web_state VARCHAR,
    web_zip VARCHAR,
    web_country VARCHAR,
    web_gmt_offset DOUBLE,
    web_tax_percentage DOUBLE
) WITH (FORMAT = 'PARQUET', EXTERNAL_LOCATION = 'file:{file_path}')
