CREATE TABLE hive.{schema}.web_returns (
    wr_returned_date_sk INTEGER,
    wr_returned_time_sk INTEGER,
    wr_item_sk INTEGER,
    wr_refunded_customer_sk INTEGER,
    wr_refunded_cdemo_sk INTEGER,
    wr_refunded_hdemo_sk INTEGER,
    wr_refunded_addr_sk INTEGER,
    wr_returning_customer_sk INTEGER,
    wr_returning_cdemo_sk INTEGER,
    wr_returning_hdemo_sk INTEGER,
    wr_returning_addr_sk INTEGER,
    wr_web_page_sk INTEGER,
    wr_reason_sk INTEGER,
    wr_order_number INTEGER,
    wr_return_quantity INTEGER,
    wr_return_amt DOUBLE,
    wr_return_tax DOUBLE,
    wr_return_amt_inc_tax DOUBLE,
    wr_fee DOUBLE,
    wr_return_ship_cost DOUBLE,
    wr_refunded_cash DOUBLE,
    wr_reversed_charge DOUBLE,
    wr_account_credit DOUBLE,
    wr_net_loss DOUBLE
) WITH (FORMAT = 'PARQUET', EXTERNAL_LOCATION = 'file:{file_path}')
