name: "ci-images (nightly)"

on:
  schedule:
    - cron: "0 5 * * *"  # 5am UTC / 1am EST

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-upstream:
    name: build (upstream)
    uses: ./.github/workflows/build.yml
    with:
      velox_repository: facebookincubator/velox
      velox_commit: main
      presto_repository: prestodb/presto
      presto_commit: master
      build_velox: true
      build_presto: true
    secrets: inherit

  test-upstream:
    name: test (upstream)
    needs: [build-upstream]
    # Run tests even if some build jobs failed; tests for missing images fail at docker pull.
    if: ${{ !cancelled() }}
    uses: ./.github/workflows/test.yml
    with:
      velox_short_sha: ${{ needs.build-upstream.outputs.velox_short_sha }}
      presto_short_sha: ${{ needs.build-upstream.outputs.presto_short_sha }}
      date: ${{ needs.build-upstream.outputs.date }}
    secrets: inherit

  build-pinned:
    name: build (pinned)
    uses: ./.github/workflows/build.yml
    with:
      velox_repository: facebookincubator/velox
      velox_commit: presto-pinned
      presto_repository: prestodb/presto
      presto_commit: master
      build_velox: true
      build_presto: true
    secrets: inherit

  test-pinned:
    name: test (pinned)
    needs: [build-pinned]
    # Run tests even if some build jobs failed; tests for missing images fail at docker pull.
    if: ${{ !cancelled() }}
    uses: ./.github/workflows/test.yml
    with:
      velox_short_sha: ${{ needs.build-pinned.outputs.velox_short_sha }}
      presto_short_sha: ${{ needs.build-pinned.outputs.presto_short_sha }}
      date: ${{ needs.build-pinned.outputs.date }}
    secrets: inherit

  build-staging:
    name: build (staging)
    uses: ./.github/workflows/build.yml
    with:
      velox_repository: ${{ vars.STABLE_VELOX_REPO }}
      velox_commit: ${{ vars.STABLE_VELOX_COMMIT }}
      presto_repository: ${{ vars.STABLE_PRESTO_REPO }}
      presto_commit: ${{ vars.STABLE_PRESTO_COMMIT }}
      build_velox: true
      build_presto: true
    secrets: inherit

  test-staging:
    name: test (staging)
    needs: [build-staging]
    # Run tests even if some build jobs failed; tests for missing images fail at docker pull.
    if: ${{ !cancelled() }}
    uses: ./.github/workflows/test.yml
    with:
      velox_short_sha: ${{ needs.build-staging.outputs.velox_short_sha }}
      presto_short_sha: ${{ needs.build-staging.outputs.presto_short_sha }}
      date: ${{ needs.build-staging.outputs.date }}
    secrets: inherit
