name: Velox Benchmark Nightly

on:
  schedule:
    - cron: '0 8 * * *'  # daily at 08:00 UTC
  workflow_dispatch:
    inputs:
      repository:
        description: 'Velox repository'
        type: string
        required: true
        default: 'rapidsai/velox'
      velox_commit:
        description: 'Velox commit SHA or branch'
        type: string
        required: true
        default: 'merged-prs'
      benchmark_type:
        description: 'Benchmark type'
        type: choice
        required: true
        default: 'tpch'
        options:
          - tpch

jobs:
  nightly:
    uses: ./.github/workflows/velox-benchmark.yml
    with:
      repository: ${{ inputs.repository || 'rapidsai/velox' }}
      velox_commit: ${{ inputs.velox_commit || 'merged-prs' }}
      benchmark_type: ${{ inputs.benchmark_type || 'tpch' }}
