name: Velox Nightly Test

on:
  schedule:
    - cron: '0 5 * * *'  # daily at 05:00 UTC
  workflow_dispatch:
    inputs:
      repository:
        description: 'Velox repository'
        type: string
        required: false
        default: 'facebookincubator/velox'
      velox_commit:
        description: 'Velox commit SHA or branch'
        type: string
        required: false
        default: 'main'
      build_target:
        description: 'Select the build target'
        type: choice
        required: false
        default: 'all'
        options:
          - all
          - cpu
          - gpu

jobs:
  nightly-test:
    uses: ./.github/workflows/velox-test.yml
    with:
      repository: ${{ inputs.repository || 'facebookincubator/velox' }}
      velox_commit: ${{ inputs.velox_commit || 'main' }}
      build_target: ${{ inputs.build_target || 'all' }}
