name: Velox Nightly Test

on:
  schedule:
    - cron: '0 5 * * *'  # daily at 05:00 UTC

jobs:
  nightly:
    runs-on: linux-amd64-gpu-l4-latest-1
    env:
      GH_TOKEN: ${{ github.token }}
      CCACHE_DIR: ${{ github.workspace }}/ccache

    steps:
      - name: Checkout this repository for CI scripts
        uses: actions/checkout@v4
        with:
          path: velox-testing

      - name: Build and Test Velox with cuDF
        uses: ./velox-testing/.github/actions/build-velox
        with:
          repository: 'facebookincubator/velox'
          velox_commit: 'main'
          run_tests: 'true'
          build_type: 'Release'
          cuda_arch: 'native'
          build_dir: 'build'
          ccache_dir: ${{ env.CCACHE_DIR }}
