name: velox-nightly

on:
  schedule:
    - cron: "0 5 * * *"  # 5am UTC / 1am EST
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  upstream:
    uses: ./.github/workflows/velox.yml
    with:
      variant_label: upstream
      velox_repository: facebookincubator/velox
      velox_commit: main
      presto_repository: prestodb/presto
      presto_commit: master
      run_tests: true
    secrets: inherit

  pinned:
    uses: ./.github/workflows/velox.yml
    with:
      variant_label: pinned
      velox_repository: facebookincubator/velox
      velox_commit: presto-pinned
      presto_repository: prestodb/presto
      presto_commit: master
      run_tests: true
    secrets: inherit

  staging:
    uses: ./.github/workflows/velox.yml
    with:
      variant_label: staging
      velox_repository: ${{ vars.STABLE_VELOX_REPO }}
      velox_commit: ${{ vars.STABLE_VELOX_COMMIT }}
      presto_repository: ${{ vars.STABLE_PRESTO_REPO }}
      presto_commit: ${{ vars.STABLE_PRESTO_COMMIT }}
      run_tests: true
    secrets: inherit
