name: Velox Nightly Test

on:
  schedule:
    # Run daily at 05:00 UTC
    - cron: '0 5 * * *'
  
  workflow_dispatch:
    inputs:
      repository:
        description: 'Velox repository'
        type: string
        required: false
        default: 'facebookincubator/velox'
      velox_commit:
        description: 'Velox commit SHA or branch'
        type: string
        required: false
        default: 'main'

jobs:
  nightly-test:
    uses: ./.github/workflows/velox-test.yml
    with:
      repository: ${{ inputs.repository || 'facebookincubator/velox' }}
      velox_commit: ${{ inputs.velox_commit || 'main' }}
