name: Velox Nightly Test

on:
  # schedule:
  #   - cron: '0 5 * * *'  # daily at 05:00 UTC
  workflow_dispatch:

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch latest Velox SHA
        id: get_sha
        run: |
          LATEST=$(curl -s https://api.github.com/repos/facebookincubator/velox/commits/main \
            | jq -r .sha)
          echo "latest=${LATEST}" >> $GITHUB_OUTPUT

      - name: Invoke Velox Test
        uses: ./.github/workflows/velox-test.yml
        with:
          velox_commit: ${{ steps.get_sha.outputs.latest }}
