name: velox-nightly

on:
  schedule:
    - cron: "0 5 * * *"  # 5am UTC / 1am EST
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  upstream:
    permissions:
      contents: read
      id-token: write
      packages: write
      attestations: write
      artifact-metadata: write
    uses: ./.github/workflows/velox.yml
    with:
      variant_label: upstream
      velox_repository: facebookincubator/velox
      velox_commit: main
      run_tests: true
      build_type: nightly
      build_variant: upstream
      run_id_suffix: ${{ github.event_name == 'workflow_dispatch' && format('-{0}', github.run_id) || '' }}
    secrets: inherit  # zizmor: ignore[secrets-inherit]
